Repository hc-sc/devops-students, pull requests merged in 2022-11, with the labels that each got.

#38 Feature/add clickable table rows to admin view
  dev-scripts/image_build.sh
  dev-scripts/run.sh
  react-website/src/App.js
  react-website/src/base/FormBase.js
  react-website/src/pages/AdminForm.js
  react-website/src/pages/AdminSignIn.js
  react-website/src/pages/Form.js
  react-website/src/pages/Table.js
  react-website/src/pages/UserForm.js
  server/routes/api.js
  server/server.js
Labels: enhancement

#42 Fixed issues in api
  server/routes/api.js
Labels: bug

#60 Feature/GitHub actions + unit-test update
  .github/workflows/node.js.yml
  react-website/package.json
  react-website/src/base/FormBase.js
  react-website/src/pages/AdminForm.js
  react-website/src/pages/AdminSignIn.js
  react-website/src/pages/Confirmation.js
  react-website/src/pages/UserForm.js
  react-website/src/tests/AdminForm.test.js
  react-website/src/tests/AdminSignIn.test.js
  react-website/src/tests/Confirmation.test.js
  react-website/src/tests/Form.test.js
  react-website/src/tests/SubmitForm.test.js
  server/main.js
  server/package-lock.json
  server/package.json
  server/routes/api.js
  server/server.js
  server/tests/admin.test.js
  server/tests/api.test.js
  server/tests/server.test.js
Labels: enhancement

#63 Merge backend.tf to main terraform branch
  server/.dockerignore
  server/.gitignore
  server/backend.tf
Labels: branch-to-branch

#66 Branch-to-branch: Create frontend terraform file
  react-website/frontend.tf
  react-website/providers.tf
Labels: branch-to-branch

#65 Branch-to-branch: Created terraform script for proxy
  proxy/.dockerignore
  proxy/providers.tf
  proxy/proxy.tf
Labels: branch-to-branch

#68 Added .gitignore to main
  .gitignore
Labels: bug
